# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-30 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='thumbnail_image',
            new_name='thumbnail',
        ),
    ]
